In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("../data/vector-0.01.csv")

In [3]:
data.head()

title  poppy seed  fish stock  fresh oysters  \
0    No-Bake Nut Cookies           0           0              0   
1  Jewell Ball'S Chicken           0           0              0   
2            Creamy Corn           0           0              0   
3          Chicken Funny           0           0              0   
4   Reeses Cups(Candy)             0           0              0   

   English cheese spread  nonfat hot fudge  White Lily  tiny peas  tube pan  \
0                      0                 0           0          0         0   
1                      0                 0           0          0         0   
2                      0                 0           0          0         0   
3                      0                 0           0          0         0   
4                      0                 0           0          0         0   

   freshly squeezed lime juice  ...  rabbit  instant coconut pudding  \
0                            0  ...       0                        0   
1                            0  ...       0                        0   
2                            0  ...       0                        0   
3                            0  ...       0                        0   
4                            0  ...       0                        0   

   extra oil  cream-style  apricot jam  light broth  wine  sauce  \
0          0            0            0            0     0      0   
1          0            0            0            0     0      0   
2          0            0            0            0     0      0   
3          0            0            0            0     0      0   
4          0            0            0            0     0      0   

   's applesauce  venison  
0              0        0  
1              0        0  
2              0        0  
3              0        0  
4              0        0  

[5 rows x 6658 columns]

In [4]:
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
data.iloc[:1, 1:].values

array([[0, 0, 0, ..., 0, 0, 0]])

In [27]:
v = data.iloc[1:2, 1:].values
sim = cosine_similarity(v, data.iloc[:, 1:].values)

In [28]:
sim.shape

(1, 22307)

In [29]:
top5 = (-sim).argsort()[:, :10]

In [30]:
sim[:, top5[0]]

array([[1.        , 0.89442719, 0.89442719, 0.89442719, 0.89442719,
        0.8660254 , 0.81649658, 0.75      , 0.75      , 0.75      ]])

In [31]:
data.iloc[top5[0]]

title  poppy seed  fish stock  fresh oysters  \
1               Jewell Ball'S Chicken           0           0              0   
7518              Party Baked Chicken           0           0              0   
5464           Baked Beef And Chicken           0           0              0   
1222   Bacon-Flavored Chicken Breasts           0           0              0   
14960                 Company Chicken           0           0              0   
1437                Chicken Casserole           0           0              0   
9438                  Elegant Chicken           0           0              0   
19630       Company Chicken Casserole           0           0              0   
9927                 Chicken Woodruff           0           0              0   
10547       Party Chicken Breast Bake           0           0              0   

       English cheese spread  nonfat hot fudge  White Lily  tiny peas  \
1                          0                 0           0          0   
7518                       0                 0           0          0   
5464                       0                 0           0          0   
1222                       0                 0           0          0   
14960                      0                 0           0          0   
1437                       0                 0           0          0   
9438                       0                 0           0          0   
19630                      0                 0           0          0   
9927                       0                 0           0          0   
10547                      0                 0           0          0   

       tube pan  freshly squeezed lime juice  ...  rabbit  \
1             0                            0  ...       0   
7518          0                            0  ...       0   
5464          0                            0  ...       0   
1222          0                            0  ...       0   
14960         0                            0  ...       0   
1437          0                            0  ...       0   
9438          0                            0  ...       0   
19630         0                            0  ...       0   
9927          0                            0  ...       0   
10547         0                            0  ...       0   

       instant coconut pudding  extra oil  cream-style  apricot jam  \
1                            0          0            0            0   
7518                         0          0            0            0   
5464                         0          0            0            0   
1222                         0          0            0            0   
14960                        0          0            0            0   
1437                         0          0            0            0   
9438                         0          0            0            0   
19630                        0          0            0            0   
9927                         0          0            0            0   
10547                        0          0            0            0   

       light broth  wine  sauce  's applesauce  venison  
1                0     0      0              0        0  
7518             0     0      0              0        0  
5464             0     0      0              0        0  
1222             0     0      0              0        0  
14960            0     0      0              0        0  
1437             0     0      0              0        0  
9438             0     0      0              0        0  
19630            0     0      0              0        0  
9927             0     0      0              0        0  
10547            0     0      0              0        0  

[10 rows x 6658 columns]

In [ ]:
# check for 5 more
# verify if all ingredients are available on the top5
# if yes -> you can do it now list
# if no -> ? (ex: add the missing ingredients to list, suggest blablabla ....)

In [13]:
import numpy as np


In [14]:
np.where(v == 1)

(array([0, 0, 0, 0]), array([1103, 1870, 2634, 6170]))

In [15]:
np.where(top5[0] == 1)

(array([0]),)

In [18]:
np.where(data.iloc[top5[0], 1:].values == 1)

(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4,
        4, 4]),
 array([1103, 1870, 2634, 6170,  808, 1103, 1870, 2634, 6170,  808, 1103,
        1870, 2634, 6170,  808, 1103, 1870, 2634, 6170,  808, 1103, 1870,
        2634, 6170]))

In [32]:
data.iloc[top5[0], 1:].values - v

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [33]:
x = data.iloc[top5[0], 1:].values - v
np.where(x < 0, 0, x).sum(-1)

array([0, 1, 1, 1, 1, 0, 2, 1, 1, 1])

In [40]:
x = data.iloc[top5[0], 1:].values - v
np.where(x == 1)

(array([1, 2, 3, 4, 6, 6, 7, 8, 9]),
 array([ 808,  808,  808,  808,  808, 4963,  752, 4790, 3697]))

In [46]:
x = data.iloc[top5[0], 1:].values - v
np.where(x[1] == 1)

(array([808]),)

In [44]:
DATA_FOLDER = "../data/"
SUBSET = 0.01
mapping = pd.read_csv(f"{DATA_FOLDER}mapping-{SUBSET}.csv", sep=",")
mapping.iloc[752]

index             752
ingredient    chicken
Name: 752, dtype: object

In [36]:
np.abs(np.where(x > 0, 0, x).sum(-1))

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1])